# Generated by Django 5.2.6 on 2025-09-08 18:33

from django.db import migrations


def update_new_building(apps):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_flat_new_building"),
    ]

    operations = [
        migrations.RunPython(update_new_building),
    ]
