# Generated by Django 5.2.6 on 2025-09-08 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_auto_20250908_2133"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complain_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текст жалобы"
                    ),
                ),
                (
                    "flat_complained",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="property.flat",
                        verbose_name="Квартира, на которую пожаловались",
                    ),
                ),
                (
                    "who_complained",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто жаловался",
                    ),
                ),
            ],
        ),
    ]
