# Generated by Django 5.2.6 on 2025-09-08 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0006_complaint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="complain_text",
            field=models.TextField(null=True, verbose_name="Текст жалобы"),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="flat_complained",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="property.flat",
                verbose_name="Квартира, на которую пожаловались",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="who_complained",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто жаловался",
            ),
        ),
    ]
