# Generated by Django 5.2.6 on 2025-09-09 17:28

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0009_flat_owner_pure_phone_alter_flat_liked_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="owner_pure_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region="RU",
                verbose_name="Нормализованный номкр владельца",
            ),
        ),
    ]
