# Generated by Django 5.2.6 on 2025-09-09 18:11

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0011_alter_flat_owner_pure_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="owner_pure_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region="RU",
                verbose_name="Нормализованный номер владельца",
            ),
        ),
    ]
