# Generated by Django 5.2.6 on 2025-09-09 18:12

from django.db import migrations
import phonenumbers
from phonenumbers import PhoneNumberFormat


def migrate_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for obj in Flat.objects.all():
        phone_number =  phonenumbers.parse(
            obj.owners_phonenumber,
            'RU'
        )
        if phonenumbers.is_valid_number(phone_number):
            obj.owner_pure_phone = phone_number
            obj.save()
        else:
            obj.owner_pure_phone = None
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0012_alter_flat_owner_pure_phone"),
    ]

    operations = [
        migrations.RunPython(
            migrate_phones,
            reverse_code=migrations.RunPython.noop
        ),
    ]
