# Generated by Django 5.2.6 on 2025-09-09 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0013_auto_20250909_2112"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_flats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто лайкнул",
            ),
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flats",
                        to="property.flat",
                        verbose_name="ФИО владельца",
                    ),
                ),
            ],
        ),
    ]
