# Generated by Django 5.2.6 on 2025-09-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0014_alter_flat_liked_by_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="owner_text",
            field=models.TextField(null=True, verbose_name="Текст жалобы"),
        ),
    ]
