# Generated by Django 5.2.6 on 2025-09-09 21:09

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0015_owner_owner_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="owner_text",
        ),
        migrations.AddField(
            model_name="owner",
            name="owner_flat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flats",
                to="property.flat",
                verbose_name="ФИО владельца",
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="owner_pure_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region="RU",
                verbose_name="Нормализованный номер владельца",
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="owners_phonenumber",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Номер владельца"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="owner_name",
            field=models.CharField(
                max_length=200, null=True, verbose_name="ФИО владельца"
            ),
        ),
    ]
