# Generated by Django 5.2.6 on 2025-09-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0016_remove_owner_owner_text_owner_owner_flat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="owner_flat",
        ),
        migrations.AddField(
            model_name="owner",
            name="owner_flat",
            field=models.ManyToManyField(
                null=True,
                related_name="flats",
                to="property.flat",
                verbose_name="Квартиры в собственности",
            ),
        ),
    ]
