# Generated by Django 5.2.6 on 2025-09-10 14:58

from django.db import migrations


def migrate_db_field(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner_name=flat.owner)


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0017_remove_owner_owner_flat_owner_owner_flat"),
    ]

    operations = [
        migrations.RunPython(migrate_db_field),
        ]
