# Generated by Django 5.2.4 on 2025-09-10 20:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0018_auto_20250910_1758"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="owner_flat",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="owner_name",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="owner_pure_phone",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="owners_phonenumber",
        ),
        migrations.AddField(
            model_name="owner",
            name="flats",
            field=models.ManyToManyField(
                null=True,
                related_name="owners",
                to="property.flat",
                verbose_name="Квартиры в собственности",
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, null=True, verbose_name="ФИО владельца"
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="phonenumber",
            field=models.CharField(
                db_index=True, max_length=20, null=True, verbose_name="Номер владельца"
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="pure_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                region="RU",
                verbose_name="Нормализованный номер владельца",
            ),
        ),
    ]
