# Generated by Django 5.2.4 on 2025-09-10 21:01

from django.db import migrations


def migrate_db_field(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(name=flat.owner)


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0019_remove_owner_owner_flat_remove_owner_owner_name_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_db_field),
        ]
