# Generated by Django 5.2.4 on 2025-09-10 21:22

from django.db import migrations


def fill_db_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(name=flat.owner)
        if not created:
            if not owner.phonenumber:
                owner.phonenumber = flat.owners_phonenumber
            if not owner.pure_phone:
                owner.pure_phone = flat.owner_pure_phone
            if not owner.flats:
                owner.flats.add(flat.id)
            owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0020_auto_20250911_0001"),
    ]

    operations = [
        migrations.RunPython(fill_db_fields),
    ]
