# Generated by Django 5.2.4 on 2025-09-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0021_auto_20250911_0022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="flats",
            field=models.ManyToManyField(
                related_name="owners",
                to="property.flat",
                verbose_name="Квартиры в собственности",
            ),
        ),
    ]
