# Generated by Django 5.2.4 on 2025-09-10 22:12

from django.db import migrations


def fill_db_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator(chunk_size=1000):
        owner, created = Owner.objects.get_or_create(name=flat.owner)
        if not created:
            if not owner.phonenumber:
                owner.phonenumber = flat.owners_phonenumber
            if not owner.pure_phone:
                owner.pure_phone = flat.owner_pure_phone
            owner.save()
        owner.flats.add(flat)
        

class Migration(migrations.Migration):

    dependencies = [
        ("property", "0022_alter_owner_flats"),
    ]

    operations = [
        migrations.RunPython(fill_db_fields),
    ]
