# Generated by Django 5.2.4 on 2025-09-10 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0023_auto_20250911_0112"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flat",
            name="owner_pure_phone",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="owners_phonenumber",
        ),
    ]
