# Generated by Django 5.2.6 on 2025-09-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0024_remove_flat_owner_pure_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="flats",
            field=models.ManyToManyField(
                related_name="owned_by",
                to="property.flat",
                verbose_name="Квартиры в собственности",
            ),
        ),
    ]
