# Generated by Django 5.2.6 on 2025-09-11 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0025_alter_owner_flats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flat",
            name="owner",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="flat_complained",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complains",
                to="property.flat",
                verbose_name="Квартира, на которую пожаловались",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="who_complained",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complains",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто жаловался",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="flats",
            field=models.ManyToManyField(
                blank=True,
                related_name="owned_by",
                to="property.flat",
                verbose_name="Квартиры в собственности",
            ),
        ),
    ]
